{{- if .Values.dbBackupRestore.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-db-backup-job
  labels:
    app: {{ template "osm-seed.name" . }}
    component: db-backup-job
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  schedule: {{ quote .Values.dbBackupRestore.schedule }}
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  startingDeadlineSeconds: 100
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-db-backup-job
            image: {{ .Values.dbBackupRestore.image.name }}:{{ .Values.dbBackupRestore.image.tag }}
            command: ['./start.sh']
            {{- if .Values.dbBackupRestore.resources.enabled }}
            resources:
              requests:
                memory: {{ .Values.dbBackupRestore.resources.requests.memory }}
                cpu: {{ .Values.dbBackupRestore.resources.requests.cpu }}
              limits:
                memory: {{ .Values.dbBackupRestore.resources.limits.memory }}
                cpu: {{ .Values.dbBackupRestore.resources.limits.cpu }}
            {{- end }}
            env:
              - name: POSTGRES_HOST
                value: {{ .Release.Name }}-db
              - name: POSTGRES_DB
                value: {{ .Values.db.env.POSTGRES_DB }}
              - name: POSTGRES_PASSWORD
                value: {{ quote .Values.db.env.POSTGRES_PASSWORD }}
              - name: POSTGRES_USER
                value: {{ .Values.db.env.POSTGRES_USER }}
              - name: DB_ACTION
                value: {{ .Values.dbBackupRestore.env.DB_ACTION }}
              - name: RESTORE_URL_FILE
                value: {{.Values.dbBackupRestore.env.RESTORE_URL_FILE}}
              - name: CLEAN_BACKUPS
                value: {{ quote .Values.dbBackupRestore.env.CLEAN_BACKUPS }}
              - name: CLOUDPROVIDER
                value: {{ .Values.cloudProvider }}
              # In case cloudProvider=aws
              {{- if eq .Values.cloudProvider "aws" }}
              - name: AWS_S3_BUCKET
                value: {{ .Values.dbBackupRestore.env.AWS_S3_BUCKET }}
              {{- end }}
              # In case cloudProvider=gcp
              {{- if eq .Values.cloudProvider "gcp" }}
              - name: GCP_STORAGE_BUCKET
                value: {{ .Values.GCP_STORAGE_BUCKET }}
              {{- end }}
          restartPolicy: OnFailure
          {{- if .Values.dbBackupRestore.nodeSelector.enabled }}
          nodeSelector:
            {{ .Values.dbBackupRestore.nodeSelector.label_key }} : {{ .Values.dbBackupRestore.nodeSelector.label_value }}
          {{- end }}
{{- end }}