{{- if .Values.tmApi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "osm-seed.fullname" . }}-tasking-manager-api
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tasking-manager-api-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  {{- if eq .Values.cloudProvider "aws" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    {{- if .Values.AWS_SSL_ARN }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.AWS_SSL_ARN }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    {{- end }}
  {{- end }}
spec:
  # In case cloudProvider=aws
  {{- if eq .Values.cloudProvider "aws" }}
  type: LoadBalancer
  {{- end }}
  # In case cloudProvider=gcp
  {{- if eq .Values.cloudProvider "gcp" }}
  type: LoadBalancer
  loadBalancerIP : {{ .Values.tmApi.staticIp }}
  {{- end }}
  # In case cloudProvider=minikube
  {{- if eq .Values.cloudProvider "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.AWS_SSL_ARN }} #FIXME: make generic
    - port: 443
      targetPort: http
      protocol: TCP
      name: https
  {{- end }}

  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-tasking-manager-api
{{- end }}