{{- if .Values.tilerServer.enabled -}}
{{ if eq .Values.tilerServer.env.TILER_CACHE_TYPE "file" }}
{{- if .Values.tilerServer.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-tiler-server-pv
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tiler-server-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  ############## Minikube ##############
  {{- if eq .Values.cloudProvider "minikube" }}
  storageClassName: local-storage
  capacity:
    storage: {{ .Values.tilerServer.persistenceDisk.localVolumeSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: { .Values.tilerServer.persistenceDisk.localVolumeHostPath | quote }}
  {{- end }}

  ############## AWS Provider ##############
  {{- if eq .Values.cloudProvider "aws" }}
  storageClassName: ""
  capacity:
    storage: {{ .Values.tilerServer.persistenceDisk.AWS_ElasticBlockStore_size }}
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: {{ .Values.tilerServer.persistenceDisk.AWS_ElasticBlockStore_volumeID }}
    fsType: ext4
  {{- end }}

  ############## GCP Provider ##############
  {{- if eq .Values.cloudProvider "gcp" }}
  storageClassName: ""
  capacity:
    storage: {{ .Values.tilerServer.persistenceDisk.GCP_gcePersistentDisk_size }}
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ .Values.tilerServer.persistenceDisk.GCP_gcePersistentDisk_pdName}}
    fsType: ext4
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-tiler-server-pv-claim
  labels:
    app: {{ template "osm-seed.name" . }}
    component: db-pd
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  ############## Minikube ##############
  {{- if eq .Values.cloudProvider "minikube" }}
  storageClassName: local-storage
  {{- else }}
  ############## Other providers ##############
  storageClassName: ""
  {{- end }}
  volumeName: {{ .Release.Name }}-tiler-server-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      ############# Minikube ##############
      {{- if eq .Values.cloudProvider "minikube" }}
      storage: {{ .Values.tilerServer.persistenceDisk.localVolumeSize }}
      {{- end }}

      ############## AWS Provider ##############
      {{- if eq .Values.cloudProvider "aws" }}
      storage: {{ .Values.tilerServer.persistenceDisk.AWS_ElasticBlockStore_size }}
      {{- end }}

      ############## GCP Provider ##############
      {{- if eq .Values.cloudProvider "gcp" }}
      storage: {{ .Values.tilerServer.persistenceDisk.GCP_gcePersistentDisk_size }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
