{{- if .Values.tilerServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tiler-server
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tiler-server-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  annotations:
    # NLB
    {{- if and  (eq .Values.ingressClassNameType "nlb" ) (eq .Values.serviceType "ClusterIP") }}
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    cert-manager.io/cluster-issuer: {{ .Release.Name }}-letsencrypt-prod-issuer
    {{- end }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: http
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-tiler-server # This is working for deployment and not for statefulset , make sure you use "s3" to storage the vtiles
{{- end }}
