{{- if and .Values.tilerServer.enabled (eq .Values.serviceType "ClusterIP") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-tiler-server
  annotations:
    cert-manager.io/cluster-issuer: {{ .Release.Name }}-letsencrypt-prod-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
    - hosts:
        {{- if .Values.tilerServer.ingressDomain }}
        - {{ .Values.tilerServer.ingressDomain }}
        {{- else }}
        - tiler.{{ .Values.domain }}
        {{- end }}
      secretName: {{ .Release.Name }}-secret-tiler-server
  rules:
    - host: {{ if .Values.tilerServer.ingressDomain }}{{ .Values.tilerServer.ingressDomain }}{{ else }}tiler.{{ .Values.domain }}{{ end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-tiler-server
                port:
                  number: 80
{{- end }}
