{{- if and .Values.tilerServer.enabled (eq .Values.serviceType "ClusterIP") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "osm-seed.fullname" . }}-ingress-tiler-server
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
spec:
  tls:
    - hosts:
      - tiler-server.{{ .Values.domain }}
      secretName: {{ template "osm-seed.fullname" . }}-secret-tiler-server

  rules:
  - host: tiler-server.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "osm-seed.fullname" . }}-tiler-server
            port:
              number: 80
{{- end }}