{{- if and .Values.tilerServer.enabled .Values.tilerServer.externalService.enabled }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-tiler-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tiler-server-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
subsets:
  - addresses:
      - ip: {{ .Values.tilerServer.externalService.ip }}
    ports:
      - name: http
        port: {{ .Values.tilerServer.externalService.port }}
        protocol: TCP
{{- end }}
