{{- if .Values.taginfoWeb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-taginfo-web
  labels:
    app: {{ template "osm-seed.name" . }}
    component: taginfo-web-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.taginfoWeb.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-taginfo-web
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-taginfo-web
    spec:
      {{- if .Values.taginfoWeb.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.taginfoWeb.serviceAccount.name }}
      automountServiceAccountToken: true
      {{- end }}
      priorityClassName: {{ .Release.Name }}-{{ .Values.taginfoWeb.priorityClass | default "medium-priority" }}
      containers:
        - name: {{ .Chart.Name }}-taginfo-web
          image: "{{ .Values.taginfoWeb.image.name }}:{{ .Values.taginfoWeb.image.tag }}"
          command:
            - /bin/sh
            - -c
            - |
              /usr/src/app/start.sh web
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 120
            timeoutSeconds: 60
          {{- if .Values.taginfoWeb.resources.enabled }}
          resources:
            {{- if .Values.taginfoWeb.resources.requests.enabled }}
            requests:
              memory: {{ .Values.taginfoWeb.resources.requests.memory }}
              cpu: {{ .Values.taginfoWeb.resources.requests.cpu }}
            {{- end }}
            {{- if .Values.taginfoWeb.resources.limits.enabled }}
            limits:
              memory: {{ .Values.taginfoWeb.resources.limits.memory }}
              cpu: {{ .Values.taginfoWeb.resources.limits.cpu }}
            {{- end }}
          {{- end }}
          env:
            {{- range $k, $v := .Values.taginfoWeb.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
      {{- if .Values.taginfoWeb.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.taginfoWeb.nodeSelector.label_key }} : {{ .Values.taginfoWeb.nodeSelector.label_value }}
      {{- end }}
      {{- if .Values.taginfoWeb.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.taginfoWeb.nodeAffinity.key }}
                    operator: In
                    values:
                    {{- range .Values.taginfoWeb.nodeAffinity.values }}
                      - {{ . | quote }}
                    {{- end }}
      {{- end }}
{{- end }}
