{{- if .Values.taginfoWeb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-taginfo
  labels:
    app: {{ template "osm-seed.name" . }}
    component: taginfo-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  {{- with .Values.taginfoWeb.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-taginfo-web
{{- end }}
