{{- if .Values.tilerImposm.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-tiler-imposm
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tiler-imposm
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app:  {{ .Release.Name }}-tiler-imposm
  serviceName: {{ .Release.Name }}-tiler-imposm
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-tiler-imposm
    spec:
      {{- if .Values.tilerImposm.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.tilerImposm.serviceAccount.name }}
      automountServiceAccountToken: true
      {{- end }}
      priorityClassName: {{ .Release.Name }}-{{ .Values.tilerImposm.priorityClass | default "medium-priority" }}
      containers:
      - name: {{ .Release.Name }}-tiler-imposm
        image: "{{ .Values.tilerImposm.image.name }}:{{ .Values.tilerImposm.image.tag }}"
        command: ['./start.sh']
        {{- if .Values.tilerImposm.livenessProbe.enabled }}
        livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - ./liveness.sh
            initialDelaySeconds: {{ .Values.tilerImposm.livenessProbe.initialDelaySeconds | default 7200 }}
            timeoutSeconds: {{ .Values.tilerImposm.livenessProbe.timeoutSeconds | default 5 }}
            periodSeconds: {{ .Values.tilerImposm.livenessProbe.periodSeconds | default 10 }}
            failureThreshold: {{ .Values.tilerImposm.livenessProbe.failureThreshold | default 3 }}
        {{- end }}
        {{- include "osm-seed.resources" .Values.tilerImposm | nindent 8 }}
        env:
          {{- range $k, $v := .Values.tilerImposm.env }}
          - name: {{ $k }}
            value: {{ $v | quote }}
          {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-tiler-db-env
        volumeMounts:
        - mountPath: {{ .Values.tilerImposm.persistenceDisk.mountPath }}
          name: tiler-imposm-storage
      restartPolicy: Always
      volumes:
        - name: tiler-imposm-storage
        {{- if .Values.tilerImposm.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tiler-imposm-data
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- include "osm-seed.nodeSelector" .Values.tilerImposm | nindent 6 }}
      {{- include "osm-seed.nodeAffinity" .Values.tilerImposm | nindent 6 }}
{{- end }}
