{{- if .Values.tilerImposm.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-tiler-imposm-sts
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tiler-imposm
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app:  {{ .Release.Name }}-tiler-imposm-sts
  serviceName: {{ .Release.Name }}-tiler-imposm
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-tiler-imposm-sts
    spec:
      {{- if .Values.tilerImposm.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.tilerImposm.serviceAccount.name }}
      automountServiceAccountToken: true
      {{- end }}
      priorityClassName: {{ .Release.Name }}-{{ .Values.tilerImposm.priorityClass | default "medium-priority" }}
      containers:
      - name: {{ .Release.Name }}-tiler-imposm-sts
        image: {{ .Values.tilerImposm.image.name }}:{{ .Values.tilerImposm.image.tag }}
        command: ['./start.sh']
        livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - ./liveness.sh
            initialDelaySeconds: 7200
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
        {{- if .Values.tilerImposm.resources.enabled }}
        resources:
          {{- if .Values.tilerImposm.resources.requests.enabled }}
          requests:
            memory: {{ .Values.tilerImposm.resources.requests.memory }}
            cpu: {{ .Values.tilerImposm.resources.requests.cpu }}
          {{- end }}
          {{- if .Values.tilerImposm.resources.limits.enabled }}
          limits:
            memory: {{ .Values.tilerImposm.resources.limits.memory }}
            cpu: {{ .Values.tilerImposm.resources.limits.cpu }}
          {{- end }}
        {{- end }}
        env:
          {{- range $k, $v := .Values.tilerImposm.env }}
          - name: {{ $k }}
            value: {{ $v | quote }}
          {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-tiler-db-cm
        volumeMounts:
        - mountPath: {{ .Values.tilerImposm.persistenceDisk.mountPath }}
          name: tiler-imposm-storage
      restartPolicy: Always
      volumes:
        - name: tiler-imposm-storage
        {{- if .Values.tilerImposm.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tiler-imposm-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if .Values.tilerImposm.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.tilerImposm.nodeSelector.label_key }} : {{ .Values.tilerImposm.nodeSelector.label_value }}
      {{- end }}
      # Affinity settings
      {{- if .Values.tilerImposm.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.tilerImposm.nodeAffinity.key }}
                    operator: In
                    values:
                    {{- range .Values.tilerImposm.nodeAffinity.values }}
                      - {{ . | quote }}
                    {{- end }}
      {{- end }}
{{- end }}
