apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ template "osm-seed.name" . }}
    chart: {{ template "osm-seed.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1 # we only ever want one replica of the db
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-db
    spec:
      containers:
        - name: {{ .Chart.Name }}-db
          image: "{{ .Values.db.image }}:{{ .Values.osmSeedVersion }}"
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-db
            - name: POSTGRES_DB
              value: {{ .Values.db.env.POSTGRES_DB }}
            - name: POSTGRES_PASSWORD
              value: {{ quote .Values.db.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_USER
              value: {{ .Values.db.env.POSTGRES_USER }}
          volumeMounts:
            - name: postgres-storage
              mountPath: "/var/lib/postgresql/data"
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi