apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-osmosis
  labels:
    app: {{ template "osm-seed.name" . }}
    chart: {{ template "osm-seed.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ quote .Values.replication.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-osmosis
            image: developmentseed/osmseed-osmosis:{{ .Values.osmSeedVersion }}
            command: ['./script.sh']
            env:
              - name: POSTGRES_HOST
                value: {{ .Release.Name }}-db
              - name: POSTGRES_DB
                value: {{ .Values.db.env.POSTGRES_DB }}
              - name: POSTGRES_PASSWORD
                value: {{ quote .Values.db.env.POSTGRES_PASSWORD }}
              - name: POSTGRES_USER
                value: {{ .Values.db.env.POSTGRES_USER }}
              - name: AWS_ACCESS_KEY_ID
                value: {{ .Values.aws.env.AWS_ACCESS_KEY_ID }}
              - name: AWS_SECRET_ACCESS_KEY
                value: {{ .Values.aws.env.AWS_SECRET_ACCESS_KEY }}
              - name: AWS_DEFAULT_REGION
                value: {{ .Values.aws.env.AWS_DEFAULT_REGION }}
              - name: S3_OSM_PATH
                value: {{ .Values.aws.env.S3_OSM_PATH }}
          restartPolicy: OnFailure