{{- if .Values.tilerServer.enabled -}}
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "osm-seed.fullname" . }}-tiler-server
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tiler-server-statefulset
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.tilerServer.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-tiler-server
  serviceName: {{ .Release.Name }}-tiler-server
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-tiler-server
    spec:
      containers:
        - name: {{ .Chart.Name }}-tiler-server
          image: "{{ .Values.tilerServer.image }}:{{ .Values.osmSeedVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.tilerServer.env.TILER_SERVER_PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.tilerServer.env.TILER_SERVER_PORT }}
            initialDelaySeconds: 600 # 10 min, because the compile process takes time.
            timeoutSeconds: 30
          {{- if .Values.tilerServer.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.tilerServer.resources.requests.memory }}
              cpu: {{ .Values.tilerServer.resources.requests.cpu }}
            limits:
              memory: {{ .Values.tilerServer.resources.limits.memory }}
              cpu: {{ .Values.tilerServer.resources.limits.cpu }}
          {{- end }}
          env:
              # tiler-db env variables
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-tiler-db
            - name: POSTGRES_DB
              value: {{ .Values.tilerDb.env.POSTGRES_DB }}
            - name: POSTGRES_PASSWORD
              value: {{ quote .Values.tilerDb.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_USER
              value: {{ .Values.tilerDb.env.POSTGRES_USER }}
            - name: POSTGRES_PORT
              value: {{ .Values.tilerDb.env.POSTGRES_PORT | quote }}
              # tiler-server env variables
            - name: TILER_SERVER_PORT
              value: {{ .Values.tilerServer.env.TILER_SERVER_PORT | quote }}
            - name: TILER_CACHE_TYPE
              value: {{ .Values.tilerServer.env.TILER_CACHE_TYPE }}
            - name: TILER_CACHE_BUCKET
              value: {{ .Values.tilerServer.env.TILER_CACHE_BUCKET }}
            - name: TILER_CACHE_BASEPATH
              value: {{ quote .Values.tilerServer.env.TILER_CACHE_BASEPATH }}
            - name: TILER_CACHE_AWS_ACCESS_KEY_ID
              value: {{ quote .Values.tilerServer.env.TILER_CACHE_AWS_ACCESS_KEY_ID }}
            - name: TILER_CACHE_AWS_SECRET_ACCESS_KEY
              value: {{ quote .Values.tilerServer.env.TILER_CACHE_AWS_SECRET_ACCESS_KEY }}
            - name: TILER_CACHE_MAX_ZOOM
              value: {{ quote .Values.tilerServer.env.TILER_CACHE_MAX_ZOOM }}
            - name: CLOUDPROVIDER
              value: {{ .Values.cloudProvider }}
            # In case cloudProvider=aws
            {{- if eq .Values.cloudProvider "aws" }}
            - name: AWS_S3_BUCKET
              value: {{ .Values.AWS_S3_BUCKET }}
            {{- end }}
            # In case cloudProvider=gcp
            {{- if eq .Values.cloudProvider "gcp" }}
            - name: GCP_STORAGE_BUCKET
              value: {{ .Values.GCP_STORAGE_BUCKET }}
            {{- end }}
          volumeMounts:
          - mountPath: /mnt/data
            name: tiler-server-storage
      restartPolicy: Always
      volumes:
        - name: tiler-server-storage
        {{- if .Values.tilerServer.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-tiler-server-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if .Values.tilerServer.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.tilerServer.nodeSelector.label_key }} : {{ .Values.tilerServer.nodeSelector.label_value }}
      {{- end }}
{{- end }}