{{- if .Values.dbBackupRestore.enabled -}}
{{- range .Values.dbBackupRestore.cronJobs }}
{{- if .enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-{{ .name }}-job
  labels:
    app: {{ template "osm-seed.name" . }}
    component: {{ .name }}-job
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  schedule: {{ quote .schedule }}
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  startingDeadlineSeconds: 100
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-{{ .name }}-job
            image: {{ .Values.dbBackupRestore.image.name }}:{{ .Values.dbBackupRestore.image.tag }}
            command: ['/start.sh']
            {{- if .resources.enabled }}
            resources:
              requests:
                memory: {{ .resources.requests.memory }}
                cpu: {{ .resources.requests.cpu }}
              limits:
                memory: {{ .resources.limits.memory }}
                cpu: {{ .resources.limits.cpu }}
            {{- end }}
            env:
            ########## Web DB section
            {{ if eq .name "web-db" }}
              - name: POSTGRES_HOST
                value: {{ .Release.Name }}-db
              - name: POSTGRES_DB
                value: {{ .Values.db.env.POSTGRES_DB }}
              - name: POSTGRES_PASSWORD
                value: {{ quote .Values.db.env.POSTGRES_PASSWORD }}
              - name: POSTGRES_USER
                value: {{ .Values.db.env.POSTGRES_USER }}
              - name: DB_ACTION
                value: {{ .Values.dbBackupRestore.env.DB_ACTION }}
              - name: RESTORE_URL_FILE
                value: {{.Values.dbBackupRestore.env.RESTORE_URL_FILE}}
              - name: CLEAN_BACKUPS
                value: {{ quote .Values.dbBackupRestore.env.CLEAN_BACKUPS }}
              - name: CLOUDPROVIDER
                value: {{ .Values.cloudProvider }}
            {{ else }}

            {{ if eq .name "osmcha-db" }}
              # TODO
            {{ else }}
            {{ if eq .name "task-manager-db" }}
              # TODO
            {{ else }}

              # In case cloudProvider=aws
              {{- if eq .Values.cloudProvider "aws" }}
              - name: AWS_S3_BUCKET
                value: {{ .Values.dbBackupRestore.env.AWS_S3_BUCKET }}
              {{- end }}
              # In case cloudProvider=gcp
              {{- if eq .Values.cloudProvider "gcp" }}
              - name: GCP_STORAGE_BUCKET
                value: {{ .Values.GCP_STORAGE_BUCKET }}
              {{- end }}
              # In case cloudProvider=azure
              {{- if eq .Values.cloudProvider "azure" }}
              - name: AZURE_STORAGE_ACCOUNT
                value: {{ .Values.AZURE_STORAGE_ACCOUNT }}
              - name: AZURE_CONTAINER_NAME
                value: {{ .Values.AZURE_CONTAINER_NAME }}
              - name: AZURE_STORAGE_CONNECTION_STRING
                value: {{ .Values.AZURE_STORAGE_CONNECTION_STRING }}
              {{- end }}
          restartPolicy: OnFailure
          {{- if .Values.dbBackupRestore.nodeSelector.enabled }}
          nodeSelector:
            {{ .Values.dbBackupRestore.nodeSelector.label_key }} : {{ .Values.dbBackupRestore.nodeSelector.label_value }}
          {{- end }}
{{- end }}
{{- end }}
{{- end }}
