{{- if .Values.tmApi.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tasking-manager-api 
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tasking-manager-api-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.tmApi.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-tasking-manager-api
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-tasking-manager-api
    spec:
      priorityClassName: {{ .Release.Name }}-{{ .Values.tmApi.priorityClass | default "medium-priority" }}
      initContainers:
        - name: db-upgrade
          image: "{{ .Values.tmApi.image.name }}:{{ .Values.tmApi.image.tag }}"
          command:
            - alembic
            - -c
            - /usr/src/app/migrations/alembic.ini
            - upgrade
            - head
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-tm-common-env
      containers:
        - name: {{ .Chart.Name }}-tasking-manager-api
          image: "{{ .Values.tmApi.image.name }}:{{ .Values.tmApi.image.tag }}"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 120
            timeoutSeconds: 30
          {{- if and .Values.tmApi.resources.enabled (or .Values.tmApi.resources.requests.enabled .Values.tmApi.resources.limits.enabled) }}
          resources:
            {{- if .Values.tmApi.resources.requests.enabled }}
            requests:
              memory: {{ .Values.tmApi.resources.requests.memory }}
              cpu: {{ .Values.tmApi.resources.requests.cpu }}
            {{- end }}
            {{- if .Values.tmApi.resources.limits.enabled }}
            limits:
              memory: {{ .Values.tmApi.resources.limits.memory }}
              cpu: {{ .Values.tmApi.resources.limits.cpu }}
            {{- end }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-tm-common-env

      {{- if .Values.tmApi.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.tmApi.nodeSelector.label_key }} : {{ .Values.tmApi.nodeSelector.label_value }}
      {{- end }}
      # Affinity settings
      {{- if .Values.tmApi.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.tmApi.nodeAffinity.key }}
                    operator: In
                    values:
                    {{- range .Values.tmApi.nodeAffinity.values }}
                      - {{ . | quote }}
                    {{- end }}
      {{- end }}
{{- end }}