{{- if .Values.tmApi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tasking-manager-api
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tasking-manager-api-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  annotations:
    # NLB
    {{- if and  (eq .Values.ingressClassNameType "nlb" ) (eq .Values.serviceType "ClusterIP") }}
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    cert-manager.io/cluster-issuer: {{ .Release.Name }}-letsencrypt-prod-issuer
    {{- end }}
spec:
  type: {{ if eq .Values.ingressClassNameType "nlb" }}{{ default "LoadBalancer" .Values.serviceType }}{{ else }}ClusterIP{{ end }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  {{- if and (eq .Values.serviceType "LoadBalancer") .Values.AWS_SSL_ARN }}
    - port: 443
      targetPort: http
      protocol: TCP
      name: https
  {{- end }}

  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-tasking-manager-api
{{- end }}