{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-web
  labels:
    app: {{ template "osm-seed.name" . }}
    component: web-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  annotations:
    {{- if and (eq .Values.serviceType "LoadBalancer") (eq .Values.ingressClassNameType "nlb") }}
    # NLB
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    {{- if .Values.AWS_SSL_ARN }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.AWS_SSL_ARN }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    {{- end }}
    {{- end }}
spec:
  # ALB -> should be ClusterIP; NLB -> LoadBalancer
  type: {{ if eq .Values.ingressClassNameType "nlb" }}{{ default "LoadBalancer" .Values.serviceType }}{{ else }}ClusterIP{{ end }}
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    {{- if and (eq .Values.ingressClassNameType "nlb") .Values.AWS_SSL_ARN }}
    - name: https
      port: 443
      targetPort: http
      protocol: TCP
    {{- end }}
{{- end }}
