{{- if .Values.web.enabled -}}
{{- if .Values.web.autoscaling.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "osm-seed.fullname" . }}-hpa-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ template "osm-seed.fullname" . }}-web
  minReplicas: {{ .Values.web.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.web.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.web.autoscaling.cpuUtilization }}
{{- end }}
{{- end }}
