{{- if .Values.memcached.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-memcached
  labels:
    app: {{ template "osm-seed.name" . }}
    component: memcached-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 11211
      targetPort: 11211  
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-memcached
{{- end }}