# The variables in this file are fake, There will be a new database.yml file in the database 
# catching the variable environments on the run process.
production:
  adapter: postgresql
  database: openstreetmap
  username: postgres
  password: 1234
  host: db
  encoding: utf8