# Generated by Django 3.2.16 on 2022-10-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("email", models.CharField(max_length=100, unique=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("pass_crypt", models.CharField(max_length=100)),
                ("creation_time", models.DateTimeField()),
                ("display_name", models.CharField(max_length=100, unique=True)),
                ("data_public", models.BooleanField()),
                ("description", models.TextField()),
                ("home_lat", models.FloatField(blank=True, null=True)),
                ("home_lon", models.FloatField(blank=True, null=True)),
                ("home_zoom", models.SmallIntegerField(blank=True, null=True)),
                ("pass_salt", models.CharField(blank=True, max_length=100, null=True)),
                ("email_valid", models.BooleanField()),
                ("new_email", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "creation_ip",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("languages", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.TextField()),
                ("terms_agreed", models.DateTimeField(blank=True, null=True)),
                ("consider_pd", models.BooleanField()),
                ("auth_uid", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "preferred_editor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("terms_seen", models.BooleanField()),
                ("description_format", models.TextField()),
                ("changesets_count", models.IntegerField()),
                ("traces_count", models.IntegerField()),
                ("diary_entries_count", models.IntegerField()),
                ("image_use_gravatar", models.BooleanField()),
                (
                    "auth_provider",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("home_tile", models.BigIntegerField(blank=True, null=True)),
                ("tou_agreed", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
