{{- if and .Values.tilerMonitorPipeline.enabled .Values.tilerMonitorPipeline.persistenceDisk.enabled }}
{{- $pd := dict "root" . "values" .Values.tilerMonitorPipeline "name" (printf "%s-tiler-monitor-pipeline-data" .Release.Name) }}
{{- if include "osm-seed.pv.static" $pd }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-tiler-monitor-pipeline-data
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tiler-monitor-pipeline
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- include "osm-seed.pv.spec" $pd | nindent 2 }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-tiler-monitor-pipeline-data
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tiler-monitor-pipeline
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- include "osm-seed.pvc.spec" $pd | nindent 2 }}
{{- end }}
