{{- if and .Values.osmchaApi.enabled .Values.osmchaApi.ingress.enabled }}
{{- $ing := .Values.osmchaApi.ingress -}}
{{- $hosts := $ing.hosts -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-osmcha-api
  labels:
    app: {{ template "osm-seed.name" . }}
    component: osmcha-api
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  {{- with $ing.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $ing.className | default .Values.ingressClassName }}
  {{- if $ing.tls.enabled }}
  tls:
    - hosts:
        {{- range $hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ $ing.tls.secretName | default (printf "%s-secret-osmcha" .Release.Name) }}
  {{- end }}
  rules:
    {{- range $hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-osmcha-api
                port:
                  number: 80
    {{- end }}
{{- end }}
