{{- if and .Values.overpassApi.enabled (eq .Values.serviceType "ClusterIP") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "osm-seed.fullname" . }}-ingress-overpass-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    {{- if .Values.overpassApi.ingressDomain }}
    - {{ .Values.overpassApi.ingressDomain }}
    {{- else }}
    - overpass-api.{{ .Values.domain }}
    {{- end }}
    secretName: {{ template "osm-seed.fullname" . }}-secret-overpass
  rules:
  - host: {{ if .Values.overpassApi.ingressDomain }}{{ .Values.overpassApi.ingressDomain }}{{ else }}overpass-api.{{ .Values.domain }}{{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "osm-seed.fullname" . }}-overpass-api
            port:
              number: 80
{{- end }}