{{- if and .Values.overpassApi.enabled .Values.overpassApi.externalService.enabled }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Release.Name }}-overpass-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "osm-seed.name" . }}
    component: overpass-api-endpoints
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
subsets:
  - addresses:
      - ip: {{ .Values.overpassApi.externalService.ip }}
    ports:
      - name: http
        port: {{ .Values.overpassApi.externalService.port }}
        protocol: TCP
{{- end }}
