{{- if .Values.overpassApi.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "osm-seed.fullname" . }}-overpass-api
  labels:
    app: {{ template "osm-seed.name" . }}
    component: overpass-api-statefulset
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-overpass-api
  serviceName: {{ .Release.Name }}-overpass-api
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-overpass-api
    spec:
      containers:
        - name: {{ .Chart.Name }}-overpass-api
          image: "{{ .Values.overpassApi.image.name }}:{{ .Values.overpassApi.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 14400 # Normal update takes 2 hours aprrox, afther that start checking liveness 
            timeoutSeconds: 30
          {{- if .Values.overpassApi.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.overpassApi.resources.requests.memory }}
              cpu: {{ .Values.overpassApi.resources.requests.cpu }}
            limits:
              memory: {{ .Values.overpassApi.resources.limits.memory }}
              cpu: {{ .Values.overpassApi.resources.limits.cpu }}
          {{- end }}
          env:
            - name: OVERPASS_META
              value: {{ .Values.overpassApi.env.OVERPASS_META | quote}}
            - name: OVERPASS_MODE
              value: {{ .Values.overpassApi.env.OVERPASS_MODE | quote}}
            - name: OVERPASS_PLANET_URL
              value: {{ .Values.overpassApi.env.OVERPASS_PLANET_URL | quote}}
            - name: OVERPASS_DIFF_URL
              value: {{ .Values.overpassApi.env.OVERPASS_DIFF_URL | quote}}
            - name: OVERPASS_RULES_LOAD
              value: {{ .Values.overpassApi.env.OVERPASS_RULES_LOAD | quote}}
            - name: OVERPASS_PLANET_PREPROCESS
              value: {{ .Values.overpassApi.env.OVERPASS_PLANET_PREPROCESS | quote}}
            - name: OVERPASS_REPLICATION_SEQUENCE_NUMBER
              value: {{ .Values.overpassApi.env.OVERPASS_REPLICATION_SEQUENCE_NUMBER | quote }}
          volumeMounts:
          - mountPath: /db
            name: overpass-api-storage
      restartPolicy: Always
      volumes:
        - name: overpass-api-storage
        {{- if .Values.overpassApi.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-overpass-api-pv-claim
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if .Values.overpassApi.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.overpassApi.nodeSelector.label_key }} : {{ .Values.overpassApi.nodeSelector.label_value }}
      {{- end }}
{{- end }}
