{{- if .Values.overpassApi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-overpass-api
  labels:
    app: {{ template "osm-seed.name" . }}
    component: overpass-api-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  annotations:
    # NLB
    {{- if eq .Values.ingressClassNameType "nlb" }}
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    {{- end }}
    # ClusterIP
    {{- if eq .Values.serviceType "ClusterIP" }}
    cert-manager.io/cluster-issuer: {{ .Release.Name }}-letsencrypt-prod-issuer
    {{- end }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  {{- if and (eq .Values.serviceType "LoadBalancer") .Values.AWS_SSL_ARN }}
    - port: 443
      targetPort: http
      protocol: TCP
      name: https
  {{- end }}
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-overpass-api
{{- end }}
