version: '3'
services:
  #####################################################
  ## OSM Database backup and restore section
  #####################################################
  db-backup-restore:
    image: osmseed-backup-restore:v1
    build:
      context: ../images/backup-restore
      dockerfile: Dockerfile
    volumes:
    - ../data/db-backup-restore-data:/mnt/data
    command: /start.sh
    env_file:
    - ../envs/.env.db
    - ../envs/.env.osmcha
    - ../envs/.env.db-utils
    - ../envs/.env.cloudprovider
