services:
  django:
    image: "ghcr.io/openhistoricalmap/osmcha-django:upstream_main"
    depends_on:
      - redis
    volumes:
      # Copy static files into a shared volume so the frontend can serve them
      - staticfiles:/app/staticfiles
    env_file: ././envs/.env.osmcha
    ports:
      - "5001:5000"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        python manage.py migrate --verbosity 3 && \
        python manage.py collectstatic --noinput && \
        gunicorn config.wsgi -t 120 -b 0.0.0.0:5000 --access-logfile - --log-level debug
  frontend:
    build:
      context: ../images/osmcha-web
      dockerfile: Dockerfile
    depends_on:
      - django
    volumes:
      # frontend serves django app's static files via shared volume
      - staticfiles:/srv/www/static/django
    env_file: ././envs/.env.osmcha

    ports:
      - "8000:80"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
volumes:
  staticfiles:
