version: '3'
services:
  osmcha-db:
    platform: linux/amd64
    image: osmseed-osmcha-db:v1
    build:
      context: ../images/osmcha-db
      dockerfile: Dockerfile
    ports:
    - '5432:5432'
    volumes:
    - ../data/osmcha-db-data:/var/lib/postgresql/data
    env_file:
    - ../envs/.env.osmcha
  osmcha-web:
    platform: linux/amd64
    image: osmseed-osmcha-web:v1
    build:
      context: ../images/osmcha-web
      dockerfile: Dockerfile
    ports:
    - '8000:8000'
    env_file:
    - ../envs/.env.osmcha
