version: '3'
services: 
  ######################################################
  ### OSM processor and also use this image as base for other containers
  ######################################################
  osm-processor:
    image: osmseed-osm-processor:v1
    build:
      context: ../images/osm-processor
      dockerfile: Dockerfile
  ######################################################
  ### Planet replication section
  ######################################################
  planet-dump:
    image: osmseed-planet-dump:v1
    build:
      context: ./images/planet-dump
      dockerfile: Dockerfile
    volumes:
      - ../data/planet-dump-data:/mnt/data
    command: >
      /bin/bash -c "
        echo 'Set cronjob for planet-dump, every 4 minutes';
        while :; do echo 'Creating the planet dump file...'; /start.sh; sleep 4m; done;
      "
    env_file:
      - ../envs/.env.db
      - ../envs/.env.db-utils
      - ../envs/.env.cloudprovider
      
