version: '3'
services:
  # #####################################################
  # ## Taginfo section
  # #####################################################
  taginfo:
    image: osmseed-taginfo:v1
    build:
      context: ../images/taginfo
      dockerfile: Dockerfile
    ports:
      - '8015:80'
    volumes:
      - ../data/taginfo-data:/usr/src/app/data
      - ${HOME}/.aws:/root/.aws:ro
      - ../images/taginfo/start.sh:/usr/src/app/start.sh
      - ../data/taginfo-data-ohm:/osm/planet/var
    command: >
      /bin/bash -c "/usr/src/app/start.sh web"

    env_file:
      - ../envs/.env.taginfo
