version: '3'
services:
  # ######################################################
  # ### Tiler DB
  # ######################################################
  tiler-db:
    image: osmseed-tiler-db:v1
    build:
      context: ../images/tiler-db
      dockerfile: Dockerfile
    ports:
      -  "5433:5432"
    volumes:
      - ../data/tiler-db-data:/var/lib/postgresql/data
    env_file:
      - ../envs/.env.tiler-db
  # ######################################################
  # ### Tiler imposm for importing data
  # ######################################################
  tiler-imposm:
    image: osmseed-tiler-imposm:v1
    build:
      context: ../images/tiler-imposm
      dockerfile: Dockerfile
    volumes:
      - ../data/tiler-imposm-data:/mnt/data
    depends_on:
      - tiler-db
    command: >
      /bin/bash -c "
        echo starting imposm!;
        sleep 1m;
        ./start.sh;
      "
    env_file:
      - ../envs/.env.tiler-db
      - ../envs/.env.tiler-imposm
  # ######################################################
  # ### Tiler imposm for importing data
  # ######################################################
  tiler-server:
    image: osmseed-tiler-server:v1
    build:
      context: ../images/tiler-server
      dockerfile: Dockerfile
    volumes:
      - ../data/tiler-server-data:/mnt/data
    depends_on:
      - tiler-db
      - tiler-imposm
    ports:
      - "9090:9090"
    command: >
      /bin/bash -c "
        echo Starting tiles server!;
        sleep 2m;
        ./start.sh;
      "
    env_file:
      - ../envs/.env.tiler-db
      - ../envs/.env.tiler-server