{{- if .Values.cgimap.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cgimap
  labels:
    app: {{ template "osm-seed.name" . }}
    component: cgimap
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.cgimap.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-cgimap
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-cgimap
    spec:
      priorityClassName: {{ .Release.Name }}-{{ .Values.cgimap.priorityClass | default "high-priority" }}
      containers:
        - name: {{ .Chart.Name }}-cgimap
          image: "{{ .Values.cgimap.image.name }}:{{ .Values.cgimap.image.tag }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /app/liveness.sh
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          {{- include "osm-seed.resources" .Values.cgimap | nindent 10 }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-web-db
            - name: POSTGRES_DB
              value: {{ .Values.webDb.env.POSTGRES_DB }}
            - name: PGPASSWORD
              value: {{ quote .Values.webDb.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_PASSWORD
              value: {{ quote .Values.webDb.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_USER
              value: {{ .Values.webDb.env.POSTGRES_USER }}
            - name: WEBSITE_STATUS
              value: {{ .Values.webApi.env.WEBSITE_STATUS }}
            - name: MEMCACHE_SERVER
              value: {{ .Release.Name }}-memcached:11211
      {{- include "osm-seed.nodeSelector" .Values.cgimap | nindent 6 }}
      # Affinity settings
      {{- if .Values.cgimap.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.cgimap.nodeAffinity.key }}
                    operator: In
                    values:
                    {{- range .Values.cgimap.nodeAffinity.values }}
                      - {{ . | quote }}
                    {{- end }}
      {{- end }}
{{- end }}
