{{- if and .Values.webDb.enabled .Values.webDb.persistenceDisk.enabled }}
{{- $pd := dict "root" . "values" .Values.webDb "name" (printf "%s-web-db-data" .Release.Name) }}
{{- if include "osm-seed.pv.static" $pd }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-web-db-data
  labels:
    app: {{ template "osm-seed.name" . }}
    component: web-db
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- include "osm-seed.pv.spec" $pd | nindent 2 }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-web-db-data
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "osm-seed.name" . }}
    component: web-db
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- include "osm-seed.pvc.spec" $pd | nindent 2 }}
{{- end }}
