{{- if .Values.webDb.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-web-db
  labels:
    app: {{ template "osm-seed.name" . }}
    component: web-db
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-web-db
  serviceName: {{ .Release.Name }}-web-db
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-web-db
    spec:
      priorityClassName: {{ .Release.Name }}-{{ .Values.webDb.priorityClass | default "high-priority" }}
      containers:
        - name: {{ .Chart.Name }}-web-db
          image: "{{ .Values.webDb.image.name }}:{{ .Values.webDb.image.tag }}"
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            # - name: GET_HOSTS_FROM
            #   value: dns
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-web-db
            - name: POSTGRES_DB
              value: {{ .Values.webDb.env.POSTGRES_DB }}
            - name: POSTGRES_PASSWORD
              value: {{ quote .Values.webDb.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_USER
              value: {{ default "postgres" .Values.webDb.env.POSTGRES_USER | quote }}
            - name: PGUSER
              value: {{ default "postgres" .Values.webDb.env.POSTGRES_USER | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
            - name: PGDATA
              value: {{ .Values.webDb.env.PGDATA }}
            - name: POD_IP
              valueFrom: { fieldRef: { fieldPath: status.podIP } }
          {{- if .Values.webDb.postgresqlConfig.enabled }}
          command:
            - "sh"
            - "-c"
            - "su postgres -c 'postgres -c config_file=/etc/postgresql/postgresql.conf'"
           {{- end }}
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - exec pg_isready --host $POD_IP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: postgres-storage
              mountPath: {{ .Values.webDb.persistenceDisk.mountPath }}
              # subPath: {{ .Values.webDb.persistenceDisk.subPath }}
            - name: shared-memory
              mountPath: /dev/shm
            {{- if .Values.webDb.postgresqlConfig.enabled }}
            - name: db-postgresql-config
              mountPath: /etc/postgresql/
            {{- end }}
          {{- include "osm-seed.resources" .Values.webDb | nindent 10 }}
      volumes:
        - name: postgres-storage
        {{- if .Values.webDb.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-web-db-data
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: shared-memory
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.webDb.sharedMemorySize }}
        {{- if .Values.webDb.postgresqlConfig.enabled }}
        - name: db-postgresql-config
          configMap:
            name: {{ .Release.Name }}-web-db-postgresql-config
        {{- end }}
      {{- include "osm-seed.nodeSelector" .Values.webDb | nindent 6 }}
      {{- include "osm-seed.nodeAffinity" .Values.webDb | nindent 6 }}
{{- end }}
