{{- if and .Values.taginfo.enabled (eq .Values.serviceType "ClusterIP") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "osm-seed.fullname" . }}-ingress-taginfo-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Release.Name }}-letsencrypt-prod-issuer
  tls:
    - hosts:
      - taginfo.{{ .Values.domain }}
      secretName: {{ template "osm-seed.fullname" . }}-secret-taginfo

  rules:
  - host: taginfo.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "osm-seed.fullname" . }}-taginfo
            port:
              number: 80
{{- end }}