{{- if .Values.taginfo.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-taginfo-cronjob
  labels:
    app: {{ template "osm-seed.name" . }}
    component: taginfo-cronjob
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  schedule: "0 0 * * 0"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 10
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-taginfo-job
            image: "{{ .Values.taginfo.image.name }}:{{ .Values.taginfo.image.tag }}"
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              /usr/src/app/start.sh data
            envFrom:
              - configMapRef:
                  name: {{ .Release.Name }}-taginfo-common-env
          restartPolicy: Never
          {{- if .Values.taginfo.nodeSelectorJob.enabled }}
          nodeSelector:
            {{ .Values.taginfo.nodeSelectorJob.label_key }} : {{ .Values.taginfo.nodeSelectorJob.label_value }}
          {{- end }}
{{- end }}
