{{- if and .Values.taginfo.enabled (eq .Values.serviceType "ClusterIP") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "osm-seed.fullname" . }}-ingress-taginfo-api
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    {{- if .Values.taginfo.ingressDomain }}
    - {{ .Values.taginfo.ingressDomain }}
    {{- else }}
    - taginfo.{{ .Values.domain }}
    {{- end }}
    secretName: {{ template "osm-seed.fullname" . }}-secret-taginfo
  rules:
  - host: {{ if .Values.taginfo.ingressDomain }}{{ .Values.taginfo.ingressDomain }}{{ else }}taginfo.{{ .Values.domain }}{{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "osm-seed.fullname" . }}-taginfo
            port:
              number: 80
{{- end }}
