{{- if .Values.adiffService.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-osmcha-adiff-service-worker
  labels:
    app: {{ .Release.Name }}-osmcha-adiff-service-worker
    environment: {{ .Values.config.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.adiffService.replicas}}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-osmcha-adiff-service-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-osmcha-adiff-service-worker
    spec:
      containers:
        - name: {{ .Release.Name }}-osmcha-adiff-service-worker
          image: "{{ .Values.adiffService.image.name }}:{{ .Values.adiffService.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - yarn update-queue
          env:
            ### Redis Server comes from osmcha-api
            - name: RedisServer
              value: redis://osmcha-redis:6379
            - name: OsmchaAdminToken
              value: {{ .Values.adiffService.env.OSMCHAADMINTOKEN }}
            - name: NumberOfWorkers
              value: {{ .Values.adiffService.env.WORKER_COUNT | quote }}
            - name: NODE_OPTIONS
              value: {{ .Values.adiffService.env.NODE_OPTIONS }}
          {{- if .Values.adiffService.nodeSelector.enabled }}
          nodeSelector:
            {{ .Values.adiffService.nodeSelector.label_key }}: {{ .Values.adiffService.nodeSelector.label_value }}
          {{- end }}
          {{- if .Values.adiffService.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.adiffService.resources.requests.memory }}
              cpu: {{ .Values.adiffService.resources.requests.cpu }}
            limits:
              memory: {{ .Values.adiffService.resources.limits.memory }}
              cpu: {{ .Values.adiffService.resources.limits.cpu }}
          {{- end }}
{{- end }}
