{{- if .Values.osmchaApi.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-osmcha-app
  labels:
    app: {{ template "osm-seed.name" . }}
    component: osmcha-app-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.osmchaApi.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-osmcha-app
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-osmcha-app
    spec:
      initContainers:
      - name: osmcha-init
        image: "{{ .Values.osmchaApi.image.name }}:{{ .Values.osmchaApi.image.tag }}"
        command:
          - /bin/sh
          - -c
          - python manage.py migrate
          - python manage.py collectstatic --noinput
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-osmcha-common-env
        volumeMounts:
        - name: staticfiles
          mountPath: /app/staticfiles
      priorityClassName: {{ .Values.osmchaApi.priorityClass | default "medium-priority" }}
      containers:
      - name: osmcha-api
        image: "{{ .Values.osmchaApi.image.name }}:{{ .Values.osmchaApi.image.tag }}"
        args: ["gunicorn", "config.wsgi", "-b", "0.0.0.0:5000", "--access-logfile", "-", "--timeout", "120", "--workers", "4", "--threads", "16"]
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 5000
          initialDelaySeconds: 60
          timeoutSeconds: 30
          
        volumeMounts:
        - name: staticfiles
          mountPath: /staticfiles
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-osmcha-common-env
        {{- if .Values.osmchaApi.resources.enabled }}
        resources:
          requests:
            memory: {{ .Values.osmchaApi.resources.requests.memory }}
            cpu: {{ .Values.osmchaApi.resources.requests.cpu }}
          limits:
            memory: {{ .Values.osmchaApi.resources.limits.memory }}
            cpu: {{ .Values.osmchaApi.resources.limits.cpu }}
        {{- end }}

      - name: frontend-nginx
        image: "{{ .Values.osmchaWeb.image.name }}:{{ .Values.osmchaWeb.image.tag }}"
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: http://localhost:5000
        volumeMounts:
          - name: staticfiles
            mountPath: /srv/www/static/django
            readOnly: true
      - name: osmcha-redis
        image: "redis:latest"
        ports:
        - containerPort: 6379
      volumes:
        - name: staticfiles
          emptyDir: {}
      {{- if .Values.osmchaApi.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.osmchaApi.nodeSelector.label_key }} : {{ .Values.osmchaApi.nodeSelector.label_value }}
      {{- end }}
{{- end }}

