{{- if .Values.osmSimpleMetrics.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-osm-simple-metrics
  labels:
    app: {{ template "osm-seed.name" . }}
    component: osm-simple-metrics
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  schedule: {{ quote .Values.osmSimpleMetrics.schedule }}
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          {{- include "osm-seed.serviceAccount" .Values.osmSimpleMetrics | nindent 10 }}
          containers:
          - name: {{ .Release.Name }}-osm-simple-metrics
            image: "{{ .Values.osmSimpleMetrics.image.name }}:{{ .Values.osmSimpleMetrics.image.tag }}"
            {{- include "osm-seed.resources" .Values.osmSimpleMetrics | nindent 12 }}
            env:
              - name: POSTGRES_HOST
                value: {{ .Release.Name }}-web-db
              - name: POSTGRES_DB
                value: {{ .Values.webDb.env.POSTGRES_DB }}
              - name: POSTGRES_PASSWORD
                value: {{ quote .Values.webDb.env.POSTGRES_PASSWORD }}
              - name: POSTGRES_USER
                value: {{ .Values.webDb.env.POSTGRES_USER }}
              - name: CLOUDPROVIDER
                value: {{ .Values.cloudProvider }}
              # In case cloudProvider=aws
              {{- if eq .Values.cloudProvider "aws" }}
              - name: AWS_S3_BUCKET
                value: {{ .Values.AWS_S3_BUCKET }}
              {{- end }}
              # In case cloudProvider=gcp
              {{- if eq .Values.cloudProvider "gcp" }}
              - name: GCP_STORAGE_BUCKET
                value: {{ .Values.GCP_STORAGE_BUCKET }}
              {{- end }}
              # In case cloudProvider=azure
              {{- if eq .Values.cloudProvider "azure" }}
              - name: AZURE_STORAGE_ACCOUNT
                value: {{ .Values.AZURE_STORAGE_ACCOUNT }}
              - name: AZURE_CONTAINER_NAME
                value: {{ .Values.AZURE_CONTAINER_NAME }}
              - name: AZURE_STORAGE_CONNECTION_STRING
                value: {{ .Values.AZURE_STORAGE_CONNECTION_STRING }}
              {{- end }}
          restartPolicy: OnFailure
          {{- include "osm-seed.nodeSelector" .Values.osmSimpleMetrics | nindent 10 }}
          {{- include "osm-seed.nodeAffinity" .Values.osmSimpleMetrics | nindent 10 }}
{{- end }}
