{{- if .Values.osmProcessor.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-osm-processor-job
  labels:
    app: {{ template "osm-seed.name" . }}
    component: osm-processor-job
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
    template:
      spec:
        containers:
        - name: {{ .Release.Name }}-osm-processor-job
          image: {{ .Values.osmProcessor.image.name }}:{{ .Values.osmProcessor.image.tag }}
          command: ['./start.sh']
          {{- if .Values.osmProcessor.resources.enabled }}   
          resources:
            requests:
              memory: {{ .Values.osmProcessor.resources.requests.memory }}
              cpu: {{ .Values.osmProcessor.resources.requests.cpu }}
            limits:
              memory: {{ .Values.osmProcessor.resources.limits.memory }}
              cpu: {{ .Values.osmProcessor.resources.limits.cpu }}
          {{- end }}
          env:
            - name: URL_FILE_TO_PROCESS
              value: {{.Values.osmProcessor.env.URL_FILE_TO_PROCESS}}
            - name: OSM_FILE_ACTION
              value: {{.Values.osmProcessor.env.OSM_FILE_ACTION}}
            - name: CLOUDPROVIDER
              value: {{ .Values.cloudProvider }}
            # In case cloudProvider=aws
            {{- if eq .Values.cloudProvider "aws" }}
            - name: AWS_S3_BUCKET
              value: {{ .Values.AWS_S3_BUCKET }}
            {{- end }}
            # In case cloudProvider=gcp
            {{- if eq .Values.cloudProvider "gcp" }}
            - name: GCP_STORAGE_BUCKET
              value: {{ .Values.GCP_STORAGE_BUCKET }}
            {{- end }}
        restartPolicy: Never
{{- end }}