{{- if .Values.planetDump.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-planet-dump
  labels:
    app: {{ template "osm-seed.name" . }}
    component: planet-dump
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  schedule: {{ quote .Values.planetDump.schedule }}
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          {{- if .Values.planetDump.serviceAccount.enabled }}
          serviceAccountName: {{ .Values.planetDump.serviceAccount.name }}
          automountServiceAccountToken: true
          {{- end }}
          containers:
          - name: {{ .Release.Name }}-planet-dump
            image: "{{ .Values.planetDump.image.name }}:{{ .Values.planetDump.image.tag }}"
            command: ['/start.sh']
            {{- include "osm-seed.resources" .Values.planetDump | nindent 12 }}
            env:
              - name: POSTGRES_HOST
                value: {{ .Release.Name }}-web-db
              - name: POSTGRES_DB
                value: {{ .Values.webDb.env.POSTGRES_DB }}
              - name: POSTGRES_PASSWORD
                value: {{ quote .Values.webDb.env.POSTGRES_PASSWORD }}
              - name: POSTGRES_USER
                value: {{ .Values.webDb.env.POSTGRES_USER }}
              - name: CLOUDPROVIDER
                value: {{ .Values.cloudProvider }}
              - name: OVERWRITE_PLANET_FILE
                value: {{ .Values.planetDump.env.OVERWRITE_PLANET_FILE | quote}}
              - name: PLANET_EXPORT_METHOD
                value: {{ .Values.planetDump.env.PLANET_EXPORT_METHOD | quote}}
              - name: DUMP_CLOUD_URL
                value: {{ .Values.planetDump.env.DUMP_CLOUD_URL | quote}}
              - name: PLANET_EPOCH_DATE
                value: {{ .Values.planetDump.env.PLANET_EPOCH_DATE | quote}}
              - name: PLANET_DUMP_NG_METADATA_URL
                value: {{ .Values.planetDump.env.PLANET_DUMP_NG_METADATA_URL | quote}}
              # In case cloudProvider=aws
              {{- if eq .Values.cloudProvider "aws" }}
              - name: AWS_S3_BUCKET
                value: {{ .Values.AWS_S3_BUCKET }}
              {{- end }}
              # In case cloudProvider=gcp
              {{- if eq .Values.cloudProvider "gcp" }}
              - name: GCP_STORAGE_BUCKET
                value: {{ .Values.GCP_STORAGE_BUCKET }}
              {{- end }}
            # In case cloudProvider=azure
            {{- if eq .Values.cloudProvider "azure" }}
            - name: AZURE_STORAGE_ACCOUNT
              value: {{ .Values.AZURE_STORAGE_ACCOUNT }}
            - name: AZURE_CONTAINER_NAME
              value: {{ .Values.AZURE_CONTAINER_NAME }}
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: {{ .Values.AZURE_STORAGE_CONNECTION_STRING }}
            {{- end }}
              # Memory optimization for osmosis
              {{- if .Values.planetDump.resources.requests }}   
              - name: MEMORY_JAVACMD_OPTIONS
                value: {{ .Values.planetDump.resources.requests.memory | default "2Gi" | quote}}
              {{- end }}
          restartPolicy: OnFailure
          {{- include "osm-seed.nodeSelector" .Values.planetDump | nindent 10 }}
          {{- include "osm-seed.nodeAffinity" .Values.planetDump | nindent 10 }}
      backoffLimit: 3
{{- end }}