{{- if .Values.nominatimApi.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-nominatim-api
  labels:
    app: {{ template "osm-seed.name" . }}
    component: nominatim-api
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-nominatim-api
  serviceName: {{ .Release.Name }}-nominatim-api
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-nominatim-api
    spec:
      priorityClassName: {{ .Release.Name }}-{{ .Values.nominatimApi.priorityClass | default "medium-priority" }}
      containers:
        - name: nominatim-api
          image: "{{ .Values.nominatimApi.image.name }}:{{ .Values.nominatimApi.image.tag }}"
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
            - name: api
              containerPort: 8080
              protocol: TCP
          env:
            {{- range $k, $v := .Values.nominatimApi.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- if .Values.nominatimApi.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.nominatimApi.startupProbe.path | default "/status" }}
              port: {{ .Values.nominatimApi.startupProbe.port | default 8080 }}
            periodSeconds: {{ .Values.nominatimApi.startupProbe.periodSeconds | default 60 }}
            timeoutSeconds: {{ .Values.nominatimApi.startupProbe.timeoutSeconds | default 30 }}
            failureThreshold: {{ .Values.nominatimApi.startupProbe.failureThreshold | default 1440 }}
          {{- end }}
          {{- if .Values.nominatimApi.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.nominatimApi.livenessProbe.path | default "/status" }}
              port: {{ .Values.nominatimApi.livenessProbe.port | default 8080 }}
            periodSeconds: {{ .Values.nominatimApi.livenessProbe.periodSeconds | default 60 }}
            timeoutSeconds: {{ .Values.nominatimApi.livenessProbe.timeoutSeconds | default 30 }}
            failureThreshold: {{ .Values.nominatimApi.livenessProbe.failureThreshold | default 6 }}
          {{- end }}
          volumeMounts:
            - name: nominatim-db-storage
              mountPath: {{ .Values.nominatimApi.persistenceDisk.mountPath }}
              subPath: {{ .Values.nominatimApi.persistenceDisk.subPath }}
          {{- include "osm-seed.resources" .Values.nominatimApi | nindent 10 }}
          
        {{- if and .Values.nominatimApi.enabled .Values.nominatimUI.enabled }}
        - name: nominatim-ui
          image: "{{ .Values.nominatimUI.image.name }}:{{ .Values.nominatimUI.image.tag }}"
          ports:
            - containerPort: 80
              name: ui
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - >
              echo "Nominatim_Config.Nominatim_API_Endpoint = 'https://{{ .Values.nominatimApi.env.NOMINATIM_API_ENDPOINT }}/';"
              >> /usr/share/nginx/html/ui/theme/config.theme.js &&
              nginx -g "daemon off;"
        {{- end }}
      volumes:
        - name: nominatim-db-storage
        {{- if .Values.nominatimApi.persistenceDisk.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-nominatim-data
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- include "osm-seed.nodeSelector" .Values.nominatimApi | nindent 6 }}
      {{- include "osm-seed.nodeAffinity" .Values.nominatimApi | nindent 6 }}
{{- end }}
