{{- if and .Values.nominatimApi.enabled .Values.nominatimApi.persistenceDisk.enabled }}
{{- $pd := dict "root" . "values" .Values.nominatimApi "name" (printf "%s-nominatim-data" .Release.Name) }}
{{- if include "osm-seed.pv.static" $pd }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-nominatim-data
  labels:
    app: {{ template "osm-seed.name" . }}
    component: nominatim-api
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- include "osm-seed.pv.spec" $pd | nindent 2 }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-nominatim-data
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "osm-seed.name" . }}
    component: nominatim-api
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- include "osm-seed.pvc.spec" $pd | nindent 2 }}
{{- end }}
