{{- if .Values.nominatimApi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nominatim-api
  labels:
    app: {{ template "osm-seed.name" . }}
    component: nominatim-api-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  annotations:
    {{- if and (eq .Values.serviceType "LoadBalancer") .Values.AWS_SSL_ARN }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.AWS_SSL_ARN }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https    
    {{- end }}
    {{- if eq .Values.serviceType "ClusterIP" }}
    cert-manager.io/cluster-issuer: {{ .Release.Name }}-letsencrypt-prod-issuer
    {{- else }}
    fake.annotation: fake
    {{- end }}
    {{- with .Values.nominatimApi.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.nominatimApi.enabled .Values.nominatimApi.externalService.enabled }}
  # External service (no selector)
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.nominatimApi.externalService.port | default "80" }} 
      protocol: TCP
  {{- else }}
  # Internal service
  type: {{ .Values.serviceType }}
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: api
    # - port: 5432
    #   protocol: TCP
    #   name: postgres
    #   targetPort: postgres
  {{- if and (eq .Values.serviceType "LoadBalancer") .Values.AWS_SSL_ARN }}
    - port: 443
      protocol: TCP
      name: https
      targetPort: apache
  {{- end }}
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-nominatim
  {{- end }}
{{- end }}
---
{{- if and .Values.nominatimApi.enabled .Values.nominatimUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nominatim-ui
  labels:
    app: {{ template "osm-seed.name" . }}
    component: nominatim-ui-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  {{- if and .Values.nominatimUI.enabled .Values.nominatimUI.externalService.enabled }}
  # External service (no selector)
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.nominatimUI.externalService.port | default "80" }} 
      protocol: TCP
  {{- else }}
  # Internal service
  type: ClusterIP
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: ui
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-nominatim
  {{- end }}
{{- end }}