{{- if .Values.webApi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-api
  labels:
    app: {{ template "osm-seed.name" . }}
    component: web-api
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  {{- with .Values.webApi.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-web-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
{{- end }}
