{{- if .Values.nominatimDb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nominatim-db
  labels:
    app: {{ template "osm-seed.name" . }}
    component: nominatim-db-service
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ template "osm-seed.name" . }}
    release: {{ .Release.Name }}
    run: {{ .Release.Name }}-nominatim-db
{{- end }}