apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osm-seed-storage-claim
spec:
  storageClassName: osm-seed-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi