name: Chartpress Publish
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Setup git
      run: git config --global user.email "noreply@developmentseed.org" && git config --global user.name "Github Action"
    - name: Install Chartpress
      run: |
        pip install -v chartpress
    - name: Bust docker mirror
      run: |
        echo '{"mtu": 1460}' | sudo dd of=/etc/docker/daemon.json &&
        sudo systemctl restart docker
    - name: Run Chartpress
      run: chartpress --push --publish-chart
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

