name: Chartpress Publish
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Install chartpress
      with:
        python-version: ${{ matrix.python-version }}
      run: |
        pip install -v chartpress
    - name: Run Chartpress
      with:
        python-version: ${{ matrix.python-version }}
      run: chartpress --push --publish-chart

