{{- if .Values.tmDb.enabled -}}
{{- if .Values.tmDb.persistenceDisk.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-tm-db-data
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tm-db
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  ############## AWS Provider ##############
  {{- if eq .Values.cloudProvider "aws" }}
  storageClassName: ""
  capacity:
    storage: {{ .Values.tmDb.persistenceDisk.AWS_ElasticBlockStore_size }}
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: {{ .Values.tmDb.persistenceDisk.AWS_ElasticBlockStore_volumeID }}
    fsType: ext4
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-tm-db-data
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tm-db
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  storageClassName: ""
  volumeName: {{ .Release.Name }}-tm-db-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      ############## AWS Provider ##############
      {{- if eq .Values.cloudProvider "aws" }}
      storage: {{ .Values.tmDb.persistenceDisk.AWS_ElasticBlockStore_size }}
      {{- end }}
{{- end }}
{{- end }}
